//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bladeDirectorClient.bladeDirector {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bladeDirector.servicesSoap")]
    public interface servicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/keepAlive", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void keepAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/keepAlive", ReplyAction="*")]
        System.Threading.Tasks.Task keepAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListNodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ListNodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListNodes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ListNodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBladesByAllocatedServer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getBladesByAllocatedServer(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBladesByAllocatedServer", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getBladesByAllocatedServerAsync(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestAnySingleNode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bladeDirectorClient.bladeDirector.resultCodeAndBladeName RequestAnySingleNode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestAnySingleNode", ReplyAction="*")]
        System.Threading.Tasks.Task<bladeDirectorClient.bladeDirector.resultCodeAndBladeName> RequestAnySingleNodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestNode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RequestNode(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RequestNode", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RequestNodeAsync(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBladeStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBladeStatus(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBladeStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBladeStatusAsync(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isBladeMine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool isBladeMine(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isBladeMine", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> isBladeMineAsync(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/releaseBlade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string releaseBlade(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/releaseBlade", ReplyAction="*")]
        System.Threading.Tasks.Task<string> releaseBladeAsync(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/forceBladeAllocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string forceBladeAllocation(string NodeIP, string newOwner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/forceBladeAllocation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> forceBladeAllocationAsync(string NodeIP, string newOwner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConfigurationOfBlade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bladeDirectorClient.bladeDirector.bladeSpec getConfigurationOfBlade(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getConfigurationOfBlade", ReplyAction="*")]
        System.Threading.Tasks.Task<bladeDirectorClient.bladeDirector.bladeSpec> getConfigurationOfBladeAsync(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentSnapshotForBlade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCurrentSnapshotForBlade(string NodeIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCurrentSnapshotForBlade", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getCurrentSnapshotForBladeAsync(string NodeIP);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class resultCodeAndBladeName : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultCode codeField;
        
        private string bladeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public resultCode code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string bladeName {
            get {
                return this.bladeNameField;
            }
            set {
                this.bladeNameField = value;
                this.RaisePropertyChanged("bladeName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum resultCode {
        
        /// <remarks/>
        success,
        
        /// <remarks/>
        bladeNotFound,
        
        /// <remarks/>
        bladeInUse,
        
        /// <remarks/>
        bladeQueueFull,
        
        /// <remarks/>
        pending,
        
        /// <remarks/>
        genericFail,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bladeOwnership))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class bladeSpec : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iscsiIPField;
        
        private string bladeIPField;
        
        private string iLOIPField;
        
        private ushort iLOPortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string iscsiIP {
            get {
                return this.iscsiIPField;
            }
            set {
                this.iscsiIPField = value;
                this.RaisePropertyChanged("iscsiIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string bladeIP {
            get {
                return this.bladeIPField;
            }
            set {
                this.bladeIPField = value;
                this.RaisePropertyChanged("bladeIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string iLOIP {
            get {
                return this.iLOIPField;
            }
            set {
                this.iLOIPField = value;
                this.RaisePropertyChanged("iLOIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ushort iLOPort {
            get {
                return this.iLOPortField;
            }
            set {
                this.iLOPortField = value;
                this.RaisePropertyChanged("iLOPort");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class bladeOwnership : bladeSpec {
        
        private long bladeIDField;
        
        private bladeStatus stateField;
        
        private string currentOwnerField;
        
        private string nextOwnerField;
        
        private System.DateTime lastKeepAliveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long bladeID {
            get {
                return this.bladeIDField;
            }
            set {
                this.bladeIDField = value;
                this.RaisePropertyChanged("bladeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bladeStatus state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string currentOwner {
            get {
                return this.currentOwnerField;
            }
            set {
                this.currentOwnerField = value;
                this.RaisePropertyChanged("currentOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string nextOwner {
            get {
                return this.nextOwnerField;
            }
            set {
                this.nextOwnerField = value;
                this.RaisePropertyChanged("nextOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime lastKeepAlive {
            get {
                return this.lastKeepAliveField;
            }
            set {
                this.lastKeepAliveField = value;
                this.RaisePropertyChanged("lastKeepAlive");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1085.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum bladeStatus {
        
        /// <remarks/>
        unused,
        
        /// <remarks/>
        releaseRequested,
        
        /// <remarks/>
        inUse,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicesSoapChannel : bladeDirectorClient.bladeDirector.servicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicesSoapClient : System.ServiceModel.ClientBase<bladeDirectorClient.bladeDirector.servicesSoap>, bladeDirectorClient.bladeDirector.servicesSoap {
        
        public servicesSoapClient() {
        }
        
        public servicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void keepAlive() {
            base.Channel.keepAlive();
        }
        
        public System.Threading.Tasks.Task keepAliveAsync() {
            return base.Channel.keepAliveAsync();
        }
        
        public string ListNodes() {
            return base.Channel.ListNodes();
        }
        
        public System.Threading.Tasks.Task<string> ListNodesAsync() {
            return base.Channel.ListNodesAsync();
        }
        
        public string getBladesByAllocatedServer(string NodeIP) {
            return base.Channel.getBladesByAllocatedServer(NodeIP);
        }
        
        public System.Threading.Tasks.Task<string> getBladesByAllocatedServerAsync(string NodeIP) {
            return base.Channel.getBladesByAllocatedServerAsync(NodeIP);
        }
        
        public bladeDirectorClient.bladeDirector.resultCodeAndBladeName RequestAnySingleNode() {
            return base.Channel.RequestAnySingleNode();
        }
        
        public System.Threading.Tasks.Task<bladeDirectorClient.bladeDirector.resultCodeAndBladeName> RequestAnySingleNodeAsync() {
            return base.Channel.RequestAnySingleNodeAsync();
        }
        
        public string RequestNode(string NodeIP) {
            return base.Channel.RequestNode(NodeIP);
        }
        
        public System.Threading.Tasks.Task<string> RequestNodeAsync(string NodeIP) {
            return base.Channel.RequestNodeAsync(NodeIP);
        }
        
        public string GetBladeStatus(string NodeIP) {
            return base.Channel.GetBladeStatus(NodeIP);
        }
        
        public System.Threading.Tasks.Task<string> GetBladeStatusAsync(string NodeIP) {
            return base.Channel.GetBladeStatusAsync(NodeIP);
        }
        
        public bool isBladeMine(string NodeIP) {
            return base.Channel.isBladeMine(NodeIP);
        }
        
        public System.Threading.Tasks.Task<bool> isBladeMineAsync(string NodeIP) {
            return base.Channel.isBladeMineAsync(NodeIP);
        }
        
        public string releaseBlade(string NodeIP) {
            return base.Channel.releaseBlade(NodeIP);
        }
        
        public System.Threading.Tasks.Task<string> releaseBladeAsync(string NodeIP) {
            return base.Channel.releaseBladeAsync(NodeIP);
        }
        
        public string forceBladeAllocation(string NodeIP, string newOwner) {
            return base.Channel.forceBladeAllocation(NodeIP, newOwner);
        }
        
        public System.Threading.Tasks.Task<string> forceBladeAllocationAsync(string NodeIP, string newOwner) {
            return base.Channel.forceBladeAllocationAsync(NodeIP, newOwner);
        }
        
        public bladeDirectorClient.bladeDirector.bladeSpec getConfigurationOfBlade(string NodeIP) {
            return base.Channel.getConfigurationOfBlade(NodeIP);
        }
        
        public System.Threading.Tasks.Task<bladeDirectorClient.bladeDirector.bladeSpec> getConfigurationOfBladeAsync(string NodeIP) {
            return base.Channel.getConfigurationOfBladeAsync(NodeIP);
        }
        
        public string getCurrentSnapshotForBlade(string NodeIP) {
            return base.Channel.getCurrentSnapshotForBlade(NodeIP);
        }
        
        public System.Threading.Tasks.Task<string> getCurrentSnapshotForBladeAsync(string NodeIP) {
            return base.Channel.getCurrentSnapshotForBladeAsync(NodeIP);
        }
    }
}
