//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.Threading.Tasks;

namespace bladeDirector.bootMenuWCF {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="bootMenuWCF.IBootMenuWCF")]
    public interface IBootMenuWCF {
        
        [OperationContract(Action="http://tempuri.org/IBootMenuWCF/addMachine", ReplyAction="http://tempuri.org/IBootMenuWCF/addMachineResponse")]
        void addMachine(string IloIP);
        
        [OperationContract(Action="http://tempuri.org/IBootMenuWCF/addMachine", ReplyAction="http://tempuri.org/IBootMenuWCF/addMachineResponse")]
        Task addMachineAsync(string IloIP);
        
        [OperationContract(Action="http://tempuri.org/IBootMenuWCF/removeMachine", ReplyAction="http://tempuri.org/IBootMenuWCF/removeMachineResponse")]
        void removeMachine(string IloIP);
        
        [OperationContract(Action="http://tempuri.org/IBootMenuWCF/removeMachine", ReplyAction="http://tempuri.org/IBootMenuWCF/removeMachineResponse")]
        Task removeMachineAsync(string IloIP);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public interface IBootMenuWCFChannel : IBootMenuWCF, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    public partial class BootMenuWCFClient : ClientBase<IBootMenuWCF>, IBootMenuWCF {
        
        public BootMenuWCFClient() {
        }
        
        public BootMenuWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BootMenuWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BootMenuWCFClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BootMenuWCFClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addMachine(string IloIP) {
            base.Channel.addMachine(IloIP);
        }
        
        public Task addMachineAsync(string IloIP) {
            return base.Channel.addMachineAsync(IloIP);
        }
        
        public void removeMachine(string IloIP) {
            base.Channel.removeMachine(IloIP);
        }
        
        public Task removeMachineAsync(string IloIP) {
            return base.Channel.removeMachineAsync(IloIP);
        }
    }
}
