//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bladeDirector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bladeDirector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table bladeConfigurations(
        ///	id primary key,
        ///    iscsiIP unique,
        ///    bladeIP unique,
        ///    iLOIP unique,
        ///    iLOPort unique
        ///	);
        ///
        ///create table bladeOwnerships(
        ///	id primary key,
        ///	bladeConfigID,
        ///	state,
        ///	currentOwner,
        ///	nextOwner,
        ///	lastKeepAlive,
        ///
        ///	foreign key (bladeConfigID) references bladeConfigurations(id)
        ///	);
        ///.
        /// </summary>
        internal static string DBCreation {
            get {
                return ResourceManager.GetString("DBCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #!ipxe
        ///
        ///ifclose net0
        ///ifopen net1
        ///set net1/ip {BLADE_IP_ISCSI}
        ///set net1/netmask {BLADE_NETMASK_ISCSI}
        ///set net1/gateway 0.0.0.0
        ///set keep-san 1
        ///echo booting with SAN device &quot;sanboot iscsi:192.168.66.254::::iqn.2016-06.lan.xd.store:{BLADE_IP_MAIN}-{HOST_IP}&quot;
        ///sanboot iscsi:192.168.66.254::::iqn.2016-06.lan.xd.store:{BLADE_IP_MAIN}-{HOST_IP}
        ///.
        /// </summary>
        internal static string ipxeTemplate {
            get {
                return ResourceManager.GetString("ipxeTemplate", resourceCulture);
            }
        }
    }
}
